In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("retail_store_sales.csv")

In [3]:
df.head()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False

In [4]:
df.shape

(12575, 11)

In [5]:
df.columns

Index(['Transaction ID', 'Customer ID', 'Category', 'Item', 'Price Per Unit',
       'Quantity', 'Total Spent', 'Payment Method', 'Location',
       'Transaction Date', 'Discount Applied'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  object
 1   Customer ID       12575 non-null  object
 2   Category          12575 non-null  object
 3   Item              11362 non-null  object
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  object
 8   Location          12575 non-null  object
 9   Transaction Date  12575 non-null  object
 10  Discount Applied  8376 non-null   object
dtypes: float64(3), object(8)
memory usage: 1.1+ MB

In [7]:
df.describe()

       Price Per Unit      Quantity   Total Spent
count    11966.000000  11971.000000  11971.000000
mean        23.365912      5.536380    129.652577
std         10.743519      2.857883     94.750697
min          5.000000      1.000000      5.000000
25%         14.000000      3.000000     51.000000
50%         23.000000      6.000000    108.500000
75%         33.500000      8.000000    192.000000
max         41.000000     10.000000    410.000000

In [8]:
df.isnull().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [16]:
# Unique values in each column
for col in df.columns:
  print(col,":", df[col].nunique())

Transaction ID : 12575
Customer ID : 25
Category : 8
Item : 200
Price Per Unit : 25
Quantity : 10
Total Spent : 227
Payment Method : 3
Location : 2
Transaction Date : 1114
Discount Applied : 2

In [17]:
df.sample(5)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
5400,TXN_2840778,CUST_16,Furniture,Item_20_FUR,33.5,1.0,33.5,Cash,In-store,2023-04-18,NaN
6515,TXN_6603773,CUST_11,Electric household essentials,Item_8_EHE,15.5,6.0,93.0,Digital Wallet,Online,2024-03-29,True
7421,TXN_8441291,CUST_18,Food,Item_8_FOOD,15.5,9.0,139.5,Digital Wallet,Online,2024-03-02,True
4359,TXN_4372415,CUST_17,Beverages,Item_2_BEV,6.5,6.0,39.0,Cash,In-store,2023-03-20,False
183,TXN_8136588,CUST_07,Milk Products,Item_16_MILK,27.5,7.0,192.5,Digital Wallet,In-store,2022-10-24,False